export const MANUAL = {
  codigo: "DOC-LOG-001",
  revision: "1.0",
  fecha: "22 de septiembre de 2026",
  titulo: "Manual técnico — Production Control",
};

export const GRUPOS = [
  {
    id: "plataforma",
    titulo: "Plataforma",
    ids: ["aplicacion", "auth", "configuracion"],
  },
  {
    id: "maestros",
    titulo: "Maestros",
    ids: ["empresa", "area", "trabajador", "maquina"],
  },
  {
    id: "produccion",
    titulo: "Producción",
    ids: ["orden-produccion", "paso-produccion", "material-orden", "minuta"],
  },
  {
    id: "operacion",
    titulo: "Operación de planta",
    ids: [
      "sesion-trabajo",
      "sesion-trabajo-paso",
      "pausa-paso-sesion",
      "registro-minuto",
      "estado-sesion",
      "estado-trabajador",
      "estado-maquina",
    ],
  },
  {
    id: "medicion",
    titulo: "Medición",
    ids: [
      "produccion-diaria",
      "indicadores",
      "indicador-sesion-minuto",
      "indicador-diario",
      "alerta",
    ],
  },
];

export const SERVICIOS = [
  {
    id: "aplicacion",
    nombre: "Aplicación y hora",
    carpeta: "src/app.controller.ts, src/app.service.ts, src/common",
    controlador: "AppController y TimezoneController",
    prefijo: "/",
    tabla: "No persiste dominio propio. Los eventos de dispositivo se registran en el servicio de aplicación.",
    resumen:
      "Punto de salud del proceso, hora de Colombia y recepción heredada de eventos de dispositivo (tolva, pedal, impacto y minuta de compatibilidad).",
    servicio:
      "AppService responde el saludo, calcula la hora America/Bogota y guarda el evento o el impacto que llega del dispositivo. TimezoneService hace el mismo cálculo de hora y el interceptor TimezoneInterceptor ajusta fechas de la respuesta HTTP. HttpLoggingInterceptor registra la petición.",
    repositorio:
      "Este módulo no abre un repositorio TypeORM. La hora no se lee de la base.",
    publicos:
      "AppController está marcado @Public() en la clase. TimezoneController también. No exigen JWT.",
    endpoints: [
      ["GET", "/", "Pública", "Mensaje de vida del proceso."],
      ["GET", "/hora-colombia", "Pública", "Fecha y hora en America/Bogota. La declaran AppController y TimezoneController."],
      ["POST", "/evento", "Pública", "Evento de estación. Exige estacion e id; tolva pide intervalo, distancia y luz; pedal pide intervalo."],
      ["GET", "/sincronizar", "Pública", "Acuse de compatibilidad. Responde guardado: 1."],
      ["POST", "/impacto", "Pública", "Impacto de estación. id admitido: stop, stop-m, continue."],
      ["POST", "/minuta", "Pública", "Minuta de compatibilidad recibida por el controlador de aplicación, distinta del recurso /minutas."],
    ],
  },
  {
    id: "auth",
    nombre: "Autenticación",
    carpeta: "src/auth",
    controlador: "AuthController",
    prefijo: "/auth",
    tabla: "auth_user",
    resumen:
      "Emite y valida el JWT que el front guarda y que la guardia global exige en el resto de la API.",
    servicio:
      "AuthService comprueba usuario y clave contra auth_user, firma el token y lo extrae del encabezado Authorization o del query token. JwtStrategy y JwtAuthGuard, registrados como guardia global en AppModule, dejan pasar solo los métodos con @Public().",
    repositorio: "Repository<AuthUser> sobre la entidad AuthUser.",
    publicos: "POST /auth/login y GET /auth/validate son públicos. El resto de la API no.",
    endpoints: [
      ["POST", "/auth/login", "Pública", "Entrega access_token, tipo Bearer, expires_in y el usuario."],
      ["GET", "/auth/validate", "Pública", "Comprueba el token del encabezado o del query token."],
    ],
  },
  {
    id: "configuracion",
    nombre: "Configuración",
    carpeta: "src/configuracion",
    controlador: "ConfiguracionController",
    prefijo: "/configuracion",
    tabla: "configuracion",
    resumen: "Parámetros globales que consumen indicadores y umbrales de alerta.",
    servicio: "ConfiguracionService lee y reemplaza el registro de configuración.",
    repositorio: "Repository<Configuracion>.",
    publicos: "Ambos métodos exigen JWT.",
    endpoints: [
      ["GET", "/configuracion", "JWT", "Devuelve la configuración vigente."],
      ["PUT", "/configuracion", "JWT", "Actualiza la configuración."],
    ],
  },
  {
    id: "empresa",
    nombre: "Empresa",
    carpeta: "src/empresa",
    controlador: "EmpresaController",
    prefijo: "/empresas",
    tabla: "empresa",
    resumen: "Catálogo de empresas.",
    servicio: "EmpresaService hace el alta, la consulta, la edición y la baja.",
    repositorio: "Repository<Empresa>.",
    publicos: "Todo el controlador exige JWT.",
    endpoints: [
      ["POST", "/empresas", "JWT", "Crea empresa."],
      ["GET", "/empresas", "JWT", "Lista empresas."],
      ["GET", "/empresas/:id", "JWT", "Una empresa."],
      ["PUT", "/empresas/:id", "JWT", "Actualiza."],
      ["DELETE", "/empresas/:id", "JWT", "Elimina."],
    ],
  },
  {
    id: "area",
    nombre: "Área",
    carpeta: "src/area",
    controlador: "AreaController",
    prefijo: "/areas",
    tabla: "area",
    resumen: "Áreas de planta. El front las carga al entrar y las comparte en AreasContext.",
    servicio: "AreaService mantiene el catálogo. Otros servicios la usan para filtrar producción, máquinas y personas.",
    repositorio: "Repository<Area>.",
    publicos: "Solo el listado es público, para que pantallas y dispositivos puedan leer áreas sin token.",
    endpoints: [
      ["POST", "/areas", "JWT", "Crea área."],
      ["GET", "/areas/:id", "JWT", "Una área."],
      ["GET", "/areas", "Pública", "Lista áreas."],
      ["PUT", "/areas/:id", "JWT", "Actualiza."],
      ["DELETE", "/areas/:id", "JWT", "Elimina."],
    ],
  },
  {
    id: "trabajador",
    nombre: "Trabajador",
    carpeta: "src/trabajador",
    controlador: "TrabajadorController",
    prefijo: "/trabajadores",
    tabla: "trabajador",
    resumen: "Personas de planta y su relación con área, sesión y estado.",
    servicio:
      "TrabajadorService consulta también sesion_trabajo, estado_sesion y estado_trabajador para armar el contexto de la persona.",
    repositorio:
      "Repository<Trabajador>, Repository<SesionTrabajo>, Repository<EstadoSesion> y Repository<EstadoTrabajador>.",
    publicos: "Las tres lecturas son públicas. Las escrituras exigen JWT.",
    endpoints: [
      ["POST", "/trabajadores", "JWT", "Crea trabajador."],
      ["GET", "/trabajadores", "Pública", "Lista trabajadores."],
      ["GET", "/trabajadores/buscar", "Pública", "Busca por texto y, si viene, por área."],
      ["GET", "/trabajadores/:id", "Pública", "Un trabajador."],
      ["PUT", "/trabajadores/:id", "JWT", "Actualiza."],
      ["DELETE", "/trabajadores/:id", "JWT", "Elimina."],
    ],
  },
  {
    id: "maquina",
    nombre: "Máquina",
    carpeta: "src/maquina",
    controlador: "MaquinaController",
    prefijo: "/maquinas",
    tabla: "Maquina",
    resumen:
      "Equipos de planta. La entidad no declara nombre de tabla: TypeORM usa el nombre de la clase, Maquina. El tipo sale del catálogo tipo-maquina.ts.",
    servicio:
      "MaquinaService cruza la máquina con su sesión, el estado de sesión y el estado de máquina.",
    repositorio:
      "Repository<Maquina>, Repository<SesionTrabajo>, Repository<EstadoSesion> y Repository<EstadoMaquina>. La máquina pertenece a un área.",
    publicos: "Búsqueda, tipos y ficha son públicos. El listado general y las escrituras exigen JWT.",
    endpoints: [
      ["POST", "/maquinas", "JWT", "Crea máquina."],
      ["GET", "/maquinas", "JWT", "Lista máquinas."],
      ["GET", "/maquinas/buscar", "Pública", "Busca por texto y, si viene, por área."],
      ["GET", "/maquinas/tipos", "Pública", "Catálogo de tipos."],
      ["GET", "/maquinas/:id", "Pública", "Una máquina. El id puede ser el que usa la ESP32."],
      ["PUT", "/maquinas/:id", "JWT", "Actualiza."],
      ["DELETE", "/maquinas/:id", "JWT", "Elimina."],
    ],
  },
  {
    id: "orden-produccion",
    nombre: "Orden de producción",
    carpeta: "src/orden-produccion",
    controlador: "OrdenProduccionController",
    prefijo: "/ordenes",
    tabla: "OrdenProduccion",
    resumen:
      "Orden a fabricar: número, producto, cantidad y estado. La tabla sigue el nombre de la clase porque @Entity() no fija otro.",
    servicio:
      "OrdenProduccionService arma el detalle con pasos, materiales, sesiones y máquina. pasos-mini devuelve la secuencia corta que consume el puesto.",
    repositorio:
      "Repository<OrdenProduccion>, Repository<PasoProduccion>, Repository<SesionTrabajo>, Repository<SesionTrabajoPaso> y Repository<Maquina>.",
    publicos: "Solo GET /ordenes/:id/pasos-mini es público.",
    endpoints: [
      ["POST", "/ordenes", "JWT", "Crea la orden."],
      ["GET", "/ordenes", "JWT", "Lista órdenes."],
      ["GET", "/ordenes/:id", "JWT", "Orden."],
      ["GET", "/ordenes/:id/pasos-mini", "Pública", "Pasos resumidos y ordenados."],
      ["GET", "/ordenes/:id/detalle", "JWT", "Orden con pasos y materiales."],
      ["DELETE", "/ordenes/:id", "JWT", "Elimina la orden."],
    ],
  },
  {
    id: "paso-produccion",
    nombre: "Paso de producción",
    carpeta: "src/paso-produccion",
    controlador: "PasoProduccionController",
    prefijo: "/pasos",
    tabla: "PasoProduccion",
    resumen: "Pasos de una orden. La tabla es el nombre de la clase PasoProduccion.",
    servicio: "PasoProduccionService lista por orden y cierra el paso cuando el puesto lo finaliza.",
    repositorio: "Repository<PasoProduccion>, ligado a OrdenProduccion.",
    publicos: "Solo el cierre del paso es público, para el dispositivo.",
    endpoints: [
      ["POST", "/pasos", "JWT", "Crea paso."],
      ["GET", "/pasos", "JWT", "Lista pasos."],
      ["GET", "/pasos/orden/:ordenId", "JWT", "Pasos de una orden."],
      ["GET", "/pasos/:id", "JWT", "Un paso."],
      ["PUT", "/pasos/:id", "JWT", "Actualiza."],
      ["PATCH", "/pasos/:id/finalizar", "Pública", "Cierra el paso."],
      ["DELETE", "/pasos/:id", "JWT", "Elimina."],
    ],
  },
  {
    id: "material-orden",
    nombre: "Material de la orden",
    carpeta: "src/material-orden",
    controlador: "MaterialOrdenController",
    prefijo: "/materiales-orden",
    tabla: "material_orden",
    resumen: "Materiales previstos o consumidos por una orden.",
    servicio: "MaterialOrdenService es el CRUD del material.",
    repositorio: "Repository<MaterialOrden>.",
    publicos: "Todo el controlador exige JWT.",
    endpoints: [
      ["POST", "/materiales-orden", "JWT", "Crea material."],
      ["GET", "/materiales-orden", "JWT", "Lista."],
      ["GET", "/materiales-orden/:id", "JWT", "Uno."],
      ["PUT", "/materiales-orden/:id", "JWT", "Actualiza."],
      ["DELETE", "/materiales-orden/:id", "JWT", "Elimina."],
    ],
  },
  {
    id: "minuta",
    nombre: "Minuta",
    carpeta: "src/minuta",
    controlador: "MinutaController",
    prefijo: "/minutas",
    tabla: "Minuta",
    resumen:
      "Minuta de producción asociada a recurso, orden y paso. No es el POST /minuta de compatibilidad del controlador de aplicación.",
    servicio: "MinutaService crea y consulta. La tabla es el nombre de la clase Minuta.",
    repositorio: "Repository<Minuta>.",
    publicos: "El alta es pública, para el puesto que abre minuta. Las lecturas exigen JWT.",
    endpoints: [
      ["POST", "/minutas", "Pública", "Crea minuta."],
      ["GET", "/minutas", "JWT", "Lista."],
      ["GET", "/minutas/:id", "JWT", "Una minuta."],
    ],
  },
  {
    id: "sesion-trabajo",
    nombre: "Sesión de trabajo",
    carpeta: "src/sesion-trabajo",
    controlador: "SesionTrabajoController",
    prefijo: "/sesiones-trabajo",
    tabla: "sesion_trabajo",
    resumen:
      "Sesión viva de una máquina: alta, consulta, serie minuto a minuto y cierre. Es el recurso que llama la ESP32.",
    servicio:
      "SesionTrabajoService coordina estados de sesión, trabajador y máquina, el paso asignado, pausas e indicadores de minuto, de sesión y diarios. Con el query esp32=true, crear y buscar la activa devuelven solo el id.",
    repositorio:
      "Repository de SesionTrabajo, EstadoSesion, EstadoTrabajador, EstadoMaquina, SesionTrabajoPaso, IndicadorSesionMinuto, PausaPasoSesion, IndicadorSesion, IndicadorDiarioDim y Maquina. Importa RegistroMinutoModule, EstadoSesionModule e IndicadorDiarioDimModule.",
    publicos:
      "Casi toda la lectura y el alta y el cierre de una sesión son públicos. Actualizar, borrar y cerrar todas las activas exigen JWT.",
    endpoints: [
      ["POST", "/sesiones-trabajo", "Pública", "Crea sesión. ?esp32=true responde solo el id."],
      ["GET", "/sesiones-trabajo", "Pública", "Lista sesiones."],
      ["GET", "/sesiones-trabajo/actuales", "Pública", "Sesiones en curso con indicadores cortos."],
      ["GET", "/sesiones-trabajo/activas", "Pública", "Activas. Query opcional trabajador."],
      ["GET", "/sesiones-trabajo/activas/resumen", "Pública", "Resumen ligero de activas."],
      ["GET", "/sesiones-trabajo/:id/orden-produccion", "Pública", "Orden y paso activos de la sesión."],
      ["GET", "/sesiones-trabajo/:id", "Pública", "Sesión con el último indicador."],
      ["GET", "/sesiones-trabajo/:id/serie-minuto", "Pública", "Serie por minuto. Query inicio y fin opcionales."],
      ["PUT", "/sesiones-trabajo/:id", "JWT", "Actualiza la sesión."],
      ["POST", "/sesiones-trabajo/:id/finalizar", "Pública", "Cierra esa sesión."],
      ["POST", "/sesiones-trabajo/finalizar-todas", "JWT", "Cierra todas las activas."],
      ["DELETE", "/sesiones-trabajo/:id", "JWT", "Elimina la sesión."],
      ["GET", "/sesiones-trabajo/maquina/:id/activa", "Pública", "Sesión activa de la máquina. ?esp32=true responde solo el id."],
      ["GET", "/sesiones-trabajo/maquina/:id/rango", "Pública", "Sesiones de la máquina entre desde y hasta."],
    ],
  },
  {
    id: "sesion-trabajo-paso",
    nombre: "Asignación sesión-paso",
    carpeta: "src/sesion-trabajo-paso",
    controlador: "SesionTrabajoPasoController",
    prefijo: "/sesion-trabajo-pasos",
    tabla: "sesion_trabajo_paso",
    resumen: "Une una sesión con el paso de la orden que está corriendo.",
    servicio: "SesionTrabajoPasoService crea y cierra asignaciones, también en lote, y limpia las que quedan de sesiones ya terminadas.",
    repositorio: "Repository<SesionTrabajoPaso>.",
    publicos:
      "Alta, lectura, edición unitaria y cierre de una asignación son públicos. El cierre masivo de huérfanas, el lote de actualización y los borrados exigen JWT.",
    endpoints: [
      ["POST", "/sesion-trabajo-pasos", "Pública", "Crea asignación."],
      ["POST", "/sesion-trabajo-pasos/batch", "Pública", "Crea en lote."],
      ["GET", "/sesion-trabajo-pasos", "Pública", "Lista."],
      ["GET", "/sesion-trabajo-pasos/por-paso/:pasoId", "Pública", "Por paso."],
      ["GET", "/sesion-trabajo-pasos/por-sesion/:sesionId", "Pública", "Por sesión."],
      ["GET", "/sesion-trabajo-pasos/:id", "Pública", "Una asignación."],
      ["PUT", "/sesion-trabajo-pasos/:id", "Pública", "Actualiza una."],
      ["POST", "/sesion-trabajo-pasos/:id/finalizar", "Pública", "Cierra una asignación."],
      ["POST", "/sesion-trabajo-pasos/finalizar-sesiones-terminadas", "JWT", "Cierra asignaciones de sesiones ya terminadas."],
      ["PUT", "/sesion-trabajo-pasos/batch", "JWT", "Actualiza en lote."],
      ["DELETE", "/sesion-trabajo-pasos/:id", "JWT", "Elimina una."],
      ["DELETE", "/sesion-trabajo-pasos/por-sesion/:sesionId", "JWT", "Elimina las de una sesión."],
      ["DELETE", "/sesion-trabajo-pasos/por-paso/:pasoId", "JWT", "Elimina las de un paso."],
    ],
  },
  {
    id: "pausa-paso-sesion",
    nombre: "Pausa de paso",
    carpeta: "src/pausa-paso-sesion",
    controlador: "No tiene controlador HTTP.",
    prefijo: "—",
    tabla: "pausa_paso_sesion",
    resumen:
      "Servicio interno. Registra la pausa de un paso dentro de la sesión. Lo usan sesión, indicadores y alertas; no se llama desde fuera.",
    servicio: "PausaPasoSesionService escribe y consulta pausas. Importa PasoProduccionModule.",
    repositorio: "Repository<PausaPasoSesion>. El módulo exporta el servicio.",
    publicos: "No expone ruta.",
    endpoints: [],
  },
  {
    id: "registro-minuto",
    nombre: "Registro por minuto",
    carpeta: "src/registro-minuto",
    controlador: "RegistroMinutoController",
    prefijo: "/registro-minuto",
    tabla: "registro_minuto",
    resumen:
      "Acumulador del puesto. El dispositivo suma en memoria y luego persiste el minuto de producción, defectos y tiempo.",
    servicio:
      "RegistroMinutoService acumula, guarda y lee el historial. Cruza la sesión, el paso asignado y el paso de producción.",
    repositorio:
      "Repository<RegistroMinuto>, Repository<SesionTrabajoPaso>, Repository<SesionTrabajo> y Repository<PasoProduccion>.",
    publicos: "Los cuatro métodos son públicos: los llama el dispositivo.",
    endpoints: [
      ["POST", "/registro-minuto/acumular", "Pública", "Suma en el acumulador en memoria."],
      ["POST", "/registro-minuto/guardar", "Pública", "Persiste el minuto."],
      ["GET", "/registro-minuto/sesion/:id", "Pública", "Historial de la sesión."],
      ["GET", "/registro-minuto/sesion/:id/ultimos", "Pública", "Últimos registros de la sesión."],
    ],
  },
  {
    id: "estado-sesion",
    nombre: "Estado de sesión",
    carpeta: "src/estado-sesion",
    controlador: "EstadoSesionController",
    prefijo: "/estados-sesion",
    tabla: "estado_sesion",
    resumen: "Historial de estado de una sesión de trabajo.",
    servicio: "EstadoSesionService es el CRUD y el borrado por sesión.",
    repositorio: "Repository<EstadoSesion>.",
    publicos: "Todo el controlador exige JWT.",
    endpoints: [
      ["POST", "/estados-sesion", "JWT", "Crea estado."],
      ["GET", "/estados-sesion", "JWT", "Lista."],
      ["GET", "/estados-sesion/por-sesion/:sesionId", "JWT", "Estados de una sesión."],
      ["GET", "/estados-sesion/:id", "JWT", "Uno."],
      ["PUT", "/estados-sesion/:id", "JWT", "Actualiza."],
      ["DELETE", "/estados-sesion/:id", "JWT", "Elimina uno."],
      ["DELETE", "/estados-sesion/por-sesion/:sesionId", "JWT", "Elimina los de una sesión."],
    ],
  },
  {
    id: "estado-trabajador",
    nombre: "Estado de trabajador",
    carpeta: "src/estado-trabajador",
    controlador: "EstadoTrabajadorController",
    prefijo: "/estados-trabajador",
    tabla: "estado_trabajador",
    resumen: "Estado de la persona, incluido el descanso.",
    servicio:
      "EstadoTrabajadorService cierra el descanso y mira la sesión y el estado de máquina para no dejar la planta inconsistente.",
    repositorio:
      "Repository<EstadoTrabajador>, Repository<SesionTrabajo> y Repository<EstadoMaquina>.",
    publicos: "Alta, historial, ficha y fin de descanso son públicos. Listado general, edición y borrado exigen JWT.",
    endpoints: [
      ["POST", "/estados-trabajador", "Pública", "Abre un estado."],
      ["GET", "/estados-trabajador", "JWT", "Lista."],
      ["GET", "/estados-trabajador/trabajador/:id", "Pública", "Historial de la persona."],
      ["GET", "/estados-trabajador/:id", "Pública", "Un estado."],
      ["PUT", "/estados-trabajador/:id", "JWT", "Actualiza."],
      ["DELETE", "/estados-trabajador/:id", "JWT", "Elimina."],
      ["POST", "/estados-trabajador/trabajador/:id/finalizar-descanso", "Pública", "Cierra el descanso."],
    ],
  },
  {
    id: "estado-maquina",
    nombre: "Estado de máquina",
    carpeta: "src/estado-maquina",
    controlador: "EstadoMaquinaController",
    prefijo: "/estados-maquina",
    tabla: "estado_maquina",
    resumen: "Estado del equipo, incluido el mantenimiento.",
    servicio:
      "EstadoMaquinaService cierra el mantenimiento y consulta la sesión y el estado del trabajador asignado.",
    repositorio:
      "Repository<EstadoMaquina>, Repository<SesionTrabajo> y Repository<EstadoTrabajador>.",
    publicos: "Alta, historial por máquina, ficha y fin de mantenimiento son públicos.",
    endpoints: [
      ["POST", "/estados-maquina", "Pública", "Abre un estado."],
      ["GET", "/estados-maquina", "JWT", "Lista."],
      ["GET", "/estados-maquina/maquina/:id", "Pública", "Historial de la máquina."],
      ["GET", "/estados-maquina/:id", "Pública", "Un estado."],
      ["PUT", "/estados-maquina/:id", "JWT", "Actualiza."],
      ["POST", "/estados-maquina/maquina/:id/finalizar-mantenimiento", "Pública", "Cierra el mantenimiento."],
      ["DELETE", "/estados-maquina/:id", "JWT", "Elimina."],
    ],
  },
  {
    id: "produccion-diaria",
    nombre: "Producción diaria",
    carpeta: "src/produccion-diaria",
    controlador: "ProduccionDiariaController",
    prefijo: "/produccion",
    tabla: "produccion_diaria",
    resumen: "Series de producción agregada por día y por mes, con filtro opcional de área.",
    servicio:
      "ProduccionDiariaService calcula las series a partir de sesiones, registros por minuto y áreas. No es un CRUD.",
    repositorio:
      "Repository<ProduccionDiaria>, Repository<SesionTrabajo>, Repository<RegistroMinuto> y Repository<Area>.",
    publicos: "Las cuatro lecturas exigen JWT.",
    endpoints: [
      ["GET", "/produccion/diaria/mes-actual", "JWT", "Días del mes en curso."],
      ["GET", "/produccion/diaria/ultimos-30-dias", "JWT", "Últimos 30 días."],
      ["GET", "/produccion/mensual/ano-actual", "JWT", "Meses del año en curso."],
      ["GET", "/produccion/mensual/ultimos-12-meses", "JWT", "Últimos 12 meses."],
    ],
  },
  {
    id: "indicadores",
    nombre: "Indicadores",
    carpeta: "src/indicadores",
    controlador: "IndicadoresController",
    prefijo: "/indicadores",
    tabla: "Lee indicador_diario_dim y las tablas de operación. No es dueño de una sola tabla.",
    resumen:
      "Consultas de cumplimiento, calidad, NPT, velocidad y resumen por producto, área, trabajador y máquina. Es el servicio que alimenta el tablero.",
    servicio:
      "IndicadoresService agrega diario, producto, tiempo real y fichas de persona o máquina. Importa SesionTrabajoModule para reutilizar el cálculo de sesión.",
    repositorio:
      "Repository de IndicadorDiarioDim, Area, Trabajador, Maquina, OrdenProduccion y RegistroMinuto.",
    publicos: "Todo el controlador exige JWT.",
    endpoints: [
      ["GET", "/indicadores/producto", "JWT", "Cumplimiento, calidad y NPT de un producto. Acepta periodo, comparativo y metas."],
      ["GET", "/indicadores/diaria/mes-actual", "JWT", "Serie diaria del mes."],
      ["GET", "/indicadores/diaria/ultimos-30-dias", "JWT", "Serie de 30 días."],
      ["GET", "/indicadores/mensual/ano-actual", "JWT", "Serie mensual del año."],
      ["GET", "/indicadores/mensual/ultimos-12-meses", "JWT", "Últimos 12 meses."],
      ["GET", "/indicadores/resumen/dia", "JWT", "Resumen del día, por área si se pide."],
      ["GET", "/indicadores/resumen/mes-actual", "JWT", "Resumen del mes."],
      ["GET", "/indicadores/realtime/area-velocidad", "JWT", "Velocidad actual por área."],
      ["GET", "/indicadores/sesiones/velocidad-normalizada", "JWT", "Curvas normalizadas de sesiones."],
      ["GET", "/indicadores/trabajadores", "JWT", "Personas con métricas en un rango."],
      ["GET", "/indicadores/trabajadores/:id/resumen", "JWT", "Resumen de una persona."],
      ["GET", "/indicadores/trabajadores/:id/diaria", "JWT", "Serie diaria de una persona."],
      ["GET", "/indicadores/maquinas", "JWT", "Máquinas con métricas en un rango."],
      ["GET", "/indicadores/maquinas/:id/resumen", "JWT", "Resumen de una máquina."],
      ["GET", "/indicadores/maquinas/:id/diaria", "JWT", "Serie diaria de una máquina."],
    ],
  },
  {
    id: "indicador-sesion-minuto",
    nombre: "Indicador por minuto de sesión",
    carpeta: "src/indicador-sesion-minuto",
    controlador: "No tiene controlador HTTP.",
    prefijo: "—",
    tabla: "indicador_sesion_minuto",
    resumen:
      "Servicio interno. Materializa la velocidad y el NPT minuto a minuto. La serie pública sale por GET /sesiones-trabajo/:id/serie-minuto.",
    servicio:
      "IndicadorSesionMinutoService calcula el minuto con pausas y la sesión. Importa SesionTrabajoModule e IndicadorDiarioDimModule.",
    repositorio:
      "Repository<IndicadorSesionMinuto>, Repository<PausaPasoSesion> y Repository<SesionTrabajo>.",
    publicos: "No expone ruta.",
    endpoints: [],
  },
  {
    id: "indicador-diario",
    nombre: "Indicador diario",
    carpeta: "src/indicador-diario-dim y src/indicador-sesion",
    controlador: "No tiene controlador HTTP.",
    prefijo: "—",
    tabla: "indicador_diario_dim e indicador_sesion",
    resumen:
      "Servicio interno de sincronización. IndicadorDiarioDimModule no está importado directo en AppModule: entra por SesionTrabajoModule y por IndicadorSesionMinutoModule. La lectura hacia el tablero la hace IndicadoresController.",
    servicio:
      "IndicadorDiarioSyncService consolida el indicador de sesión en el agregado diario.",
    repositorio: "Repository<IndicadorDiarioDim> y Repository<IndicadorSesion>.",
    publicos: "No expone ruta.",
    endpoints: [],
  },
  {
    id: "alerta",
    nombre: "Alertas",
    carpeta: "src/alerta",
    controlador: "AlertaController y AlertaConfigController",
    prefijo: "/alertas",
    tabla: "alerta, alerta_tipo y, para umbrales, configuracion",
    resumen: "Alertas de persona y de máquina, y los umbrales que deciden cuándo disparan.",
    servicio:
      "AlertaService cruza pausas, asignaciones, sesiones, registros y máquinas con el tipo de alerta. Los umbrales los lee y escribe sobre configuración.",
    repositorio:
      "Repository de Alerta, AlertaTipo, PausaPasoSesion, SesionTrabajoPaso, SesionTrabajo, Trabajador, RegistroMinuto y Maquina. Importa ConfiguracionModule.",
    publicos: "Todo exige JWT.",
    endpoints: [
      ["GET", "/alertas", "JWT", "Alertas generales."],
      ["GET", "/alertas/trabajador/rango", "JWT", "Alertas de una persona en un rango."],
      ["GET", "/alertas/maquina/rango", "JWT", "Alertas de una máquina en un rango."],
      ["GET", "/alertas/umbrales", "JWT", "Umbrales vigentes."],
      ["PUT", "/alertas/umbrales", "JWT", "Actualiza umbrales."],
    ],
  },
];

export function servicioPorId(id) {
  return SERVICIOS.find((item) => item.id === id) || null;
}
